image:
  repository: jammsen/sons-of-the-forest-dedicated-server
  tag: latest

service:
  type: ClusterIP

resources:
  requests:
    memory: 16G
    cpu: 6.0

volumes:
  gamePVC:
    size: 50Gi
  steamcmdPVC:
    size: 50Gi
  winePVC:
    size: 50Gi
  storageClassName: "longhorn"

config:
  hostIP: "0.0.0.0"
  gamePort: "8766"
  queryPort: "27016"
  blobSyncPort: "9700"
  alwaysUpdateOnStart: "1"
  hostNetwork: "false"

serverConfig:
  ipAddress: "0.0.0.0"
  serverName: "There's a snake in my boot"
  maxPlayers: "8"
  password: "changemenow"
  saveSlot: "1"
  saveMode: "Continue"
  gameMode: "Normal"
  saveInterval: "600"
  idleDayCycleSpeed: "0.0"
  idleTargetFramerate: "5"
  activeTargetFramerate: "60"
  logFilesEnabled: "false"
  timestampLogFilenames: "true"
  timestampLogEntries: "true"
  gameplayTreeRegrowth: "true"
  structureDamage: "true"
  enemySpawn: "true"
  enemyHealth: "Normal"
  enemyDamage: "Normal"
  enemyArmour: "Normal"
  enemyAggression: "Normal"
  animalSpawnRate: "Normal"
  environmentStartingSeason: "Summer"
  environmentSeasonLength: "Default"
  environmentDayLength: "Default"
  environmentPrecipitationFrequency: "Default"
  survivalConsumableEffects: "Normal"
  survivalPlayerStatsDamage: "Off"
  survivalColdPenalties: "Off"
  survivalReducedFoodInContainers: "false"
  survivalSingleUseContainers: "false"
  lanOnly: "false"
  skipNetworkAccessibilityTest: "false"
