apiVersion: v1
data:
  dedicatedserver.cfg: |2+
    {
      "IpAddress": {{ .Values.serverConfig.ipAddress | quote }},
      "GamePort": {{ .Values.config.gamePort | int }},
      "QueryPort": {{ .Values.config.queryPort | int }},
      "BlobSyncPort": {{ .Values.config.blobSyncPort | int }},
      "ServerName": {{ .Values.serverConfig.serverName | quote }},
      "MaxPlayers": {{ .Values.serverConfig.maxPlayers | int }},
      "Password": {{ .Values.serverConfig.password | quote }},
      "SaveSlot": {{ .Values.serverConfig.saveSlot | int }},
      "SaveMode": {{ .Values.serverConfig.saveMode | quote }},
      "GameMode": {{ .Values.serverConfig.gameMode | quote }},
      "SaveInterval": {{ .Values.serverConfig.saveInterval | int }},
      "IdleDayCycleSpeed": {{ .Values.serverConfig.idleDayCycleSpeed | float64 }},
      "IdleTargetFramerate": {{ .Values.serverConfig.idleTargetFramerate | int }},
      "ActiveTargetFramerate": {{ .Values.serverConfig.activeTargetFramerate |int }},
      "LogFilesEnabled": {{ .Values.serverConfig.logFilesEnabled }},
      "TimestampLogFilenames": {{ .Values.serverConfig.timestampLogFilenames }},
      "TimestampLogEntries": {{ .Values.serverConfig.timestampLogEntries }},
      "GameSettings": {
        "Gameplay.TreeRegrowth": {{ .Values.serverConfig.gameplayTreeRegrowth }},
        "Structure.Damage": {{ .Values.serverConfig.structureDamage }}
      },
      "CustomGameModeSettings": {
        "GameSetting.Vail.EnemySpawn": {{ .Values.serverConfig.enemySpawn }},
        "GameSetting.Vail.EnemyHealth": {{ .Values.serverConfig.enemyHealth | quote }},
        "GameSetting.Vail.EnemyDamage": {{ .Values.serverConfig.enemyDamage | quote }},
        "GameSetting.Vail.EnemyArmour": {{ .Values.serverConfig.enemyArmour | quote }},
        "GameSetting.Vail.EnemyAggression": {{ .Values.serverConfig.enemyAggression | quote }},
        "GameSetting.Vail.AnimalSpawnRate": {{ .Values.serverConfig.animalSpawnRate | quote }},
        "GameSetting.Environment.StartingSeason": {{ .Values.serverConfig.environmentStartingSeason | quote }},
        "GameSetting.Environment.SeasonLength": {{ .Values.serverConfig.environmentSeasonLength | quote }},
        "GameSetting.Environment.DayLength": {{ .Values.serverConfig.environmentDayLength | quote }},
        "GameSetting.Environment.PrecipitationFrequency": {{ .Values.serverConfig.environmentPrecipitationFrequency | quote }},
        "GameSetting.Survival.ConsumableEffects": {{ .Values.serverConfig.survivalConsumableEffects | quote }},
        "GameSetting.Survival.PlayerStatsDamage": {{ .Values.serverConfig.survivalPlayerStatsDamage | quote }},
        "GameSetting.Survival.ColdPenalties": {{ .Values.serverConfig.survivalColPenalties | quote }},
        "GameSetting.Survival.ReducedFoodInContainers": {{ .Values.serverConfig.survivalReducedFoodInContainers }},
        "GameSetting.Survival.SingleUseContainers": {{ .Values.serverConfig.survivalSingleUseContainers }}
      },
      "LanOnly": {{ .Values.serverConfig.lanOnly }},
      "SkipNetworkAccessibilityTest": {{ .Values.serverConfig.skipNetworkAccessibilityTest }}
    }

kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-map"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"

