apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-map "
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
 
data:
game_config: {{ .Files.Get .Values.config.configPath | indent 4 }}
