apiVersion: v1
data:
  dedicatedserver.cfg: |2+
     {
      "IpAddress": "0.0.0.0",
      "GamePort": 8766,
      "QueryPort": 27016,
      "BlobSyncPort": 9700,
      "ServerName": "There's a snake in my boot",
      "MaxPlayers": 16,
      "Password": "changemenow",
      "SaveSlot": 1,
      "SaveMode": "Continue",
      "GameMode": "Normal",
      "SaveInterval": 600,
      "IdleDayCycleSpeed": 0.0,
      "IdleTargetFramerate": 5,
      "ActiveTargetFramerate": 60,
      "LogFilesEnabled": false,
      "TimestampLogFilenames": true,
      "TimestampLogEntries": true,
      "GameSettings": {
        "Gameplay.TreeRegrowth": true,
        "Structure.Damage": true
      },
      "CustomGameModeSettings": {
        "GameSetting.Vail.EnemySpawn": true,
        "GameSetting.Vail.EnemyHealth": "Normal",
        "GameSetting.Vail.EnemyDamage": "Normal",
        "GameSetting.Vail.EnemyArmour": "Normal",
        "GameSetting.Vail.EnemyAggression": "Normal",
        "GameSetting.Vail.AnimalSpawnRate": "Normal",
        "GameSetting.Environment.StartingSeason": "Summer",
        "GameSetting.Environment.SeasonLength": "Default",
        "Structure.Damage": "true",
        "GameSetting.Environment.DayLength": "Default",
        "GameSetting.Environment.PrecipitationFrequency": "Default",
        "GameSetting.Survival.ConsumableEffects": "Normal",
        "GameSetting.Survival.PlayerStatsDamage": "Off",
        "GameSetting.Survival.ColdPenalties": "Off",
        "GameSetting.Survival.ReducedFoodInContainers": false,
        "GameSetting.Survival.SingleUseContainers": false
      },
      "LanOnly": true,
      "SkipNetworkAccessibilityTest": false
    }

kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-map"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"

