apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: "{{ .Chart.Name }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: ALWAYS_UPDATE_ON_START
          value: {{ .Values.config.alwaysUpdateOnStart | quote }}
        ports:
        - name: game-port
          containerPort: {{ .Values.config.gamePort | int }}
          hostIP: {{ .Values.config.hostIP }}
          hostPort: {{ .Values.config.gamePort | int }}
          protocol: UDP
        - name: query-port
          containerPort: {{ .Values.config.queryPort | int }}
          hostIP: {{ .Values.config.hostIP }}
          hostPort: {{ .Values.config.queryPort | int }}
          protocol: UDP
        - name: blobsync-port
          containerPort: {{ .Values.config.blobSyncPort | int }}
          hostIP: {{ .Values.config.hostIP }}
          hostPort: {{ .Values.config.blobSyncPort | int }}
          protocol: UDP
        volumeMounts:
        - name: game
          mountPath: /sonsoftheforest
        - name: steamcmd
          mountPath: /steamcmd
        - name: wine
          mountPath: /winedata
        - name: config
          mountPath: sonsoftheforest/userdata/dedicatedserver.cfg
          subPath: dedicatedserver.cfg
        securityContext:
          allowPrivilegeEscalation: false
      volumes:
      - name: game
        persistentVolumeClaim:
          claimName: "{{ .Chart.Name }}-game"
      - name: steamcmd
        persistentVolumeClaim:
          claimName: "{{ .Chart.Name }}-steamcmd"
      - name: wine
        persistentVolumeClaim:
          claimName: "{{ .Chart.Name }}-wine"
      - name: config
        configMap:
          name: "{{ .Chart.Name }}-map"
          items:
            - key: dedicatedserver.cfg
              path: sonsoftheforest/userdata/dedicatedserver.cfg
      terminationGracePeriodSeconds: 90

